/**
 * Delivery for the weekly Marketing Director briefing — sends via Resend (email) and
 * commits the markdown to the repo via the GitHub REST API.
 *
 * Both calls fail soft: if env vars aren't set or the API call errors, we log and continue
 * so the cron itself stays green and the JSON response always returns the briefing content.
 */

import { resend } from '@/lib/email/resend-client';

const REPO_OWNER = process.env.GITHUB_REPO_OWNER ?? 'allan-cmyk';
const REPO_NAME = process.env.GITHUB_REPO_NAME ?? 'PartyOn2';
const REPO_BRANCH = process.env.GITHUB_REPO_BRANCH ?? 'main';

export interface DeliveryResult {
  email: { sent: boolean; error?: string };
  commit: { committed: boolean; sha?: string; url?: string; error?: string };
}

interface BriefingPayload {
  weekLabel: string;            // e.g. "2026-W18"
  stageA: string;               // deterministic markdown
  stageB: string | null;        // LLM narrative (null if not generated)
  to: string;                   // recipient email
}

export async function deliverBriefing(payload: BriefingPayload): Promise<DeliveryResult> {
  const [emailRes, commitRes] = await Promise.all([
    sendEmail(payload).catch((e) => ({ sent: false, error: errMsg(e) })),
    commitToRepo(payload).catch((e) => ({ committed: false, error: errMsg(e) })),
  ]);
  return { email: emailRes, commit: commitRes };
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

/* -------------------- Email via Resend -------------------- */

async function sendEmail(p: BriefingPayload): Promise<{ sent: boolean; error?: string }> {
  if (!resend) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const subject = `Marketing weekly briefing — ${p.weekLabel}`;
  const html = renderHtml(p);
  const text = renderText(p);
  const fromName = 'Party On Delivery — Marketing Director';
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'orders@partyondelivery.com';

  await resend.emails.send({
    from: `${fromName} <${fromEmail}>`,
    to: p.to,
    subject,
    html,
    text,
  });
  return { sent: true };
}

function renderHtml(p: BriefingPayload): string {
  const stageBHtml = p.stageB
    ? `<hr/><h2>Narrative analysis (Claude)</h2><pre style="white-space:pre-wrap;font-family:inherit;font-size:15px;line-height:1.5;">${escapeHtml(p.stageB)}</pre>`
    : '<hr/><p style="color:#888"><em>Stage B narrative analysis was not generated this week — check the cron logs.</em></p>';

  return `<!doctype html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:760px;margin:0 auto;padding:32px;color:#111;">
  <h1 style="font-size:24px;margin-bottom:4px;">Marketing weekly briefing — ${p.weekLabel}</h1>
  <p style="color:#666;margin-top:0;font-size:14px;">Auto-generated by the Party On Delivery analytics pipeline. Also committed to the repo at <code>docs/marketing/weekly/${p.weekLabel}.md</code>.</p>
  <hr/>
  <h2>Data summary</h2>
  <pre style="white-space:pre-wrap;font-family:inherit;font-size:15px;line-height:1.5;">${escapeHtml(p.stageA)}</pre>
  ${stageBHtml}
</body>
</html>`;
}

function renderText(p: BriefingPayload): string {
  return [p.stageA, p.stageB ? `\n---\n\n${p.stageB}` : ''].join('');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/* -------------------- Commit to GitHub repo -------------------- */

async function commitToRepo(p: BriefingPayload): Promise<DeliveryResult['commit']> {
  const token = process.env.GITHUB_REPO_TOKEN;
  if (!token) {
    return { committed: false, error: 'GITHUB_REPO_TOKEN not configured' };
  }

  // Commit Stage A and (if present) Stage B as two separate files in one commit attempt each.
  // We use the simple "create or update file" endpoint — fine for low volume.
  const stageARes = await putFile(token, `docs/marketing/weekly/${p.weekLabel}.md`, p.stageA, `chore(marketing): weekly briefing ${p.weekLabel}`);
  let stageBSha: string | undefined;
  let stageBHtmlUrl: string | undefined;

  if (p.stageB) {
    const stageBRes = await putFile(
      token,
      `docs/marketing/weekly/${p.weekLabel}-director.md`,
      p.stageB,
      `chore(marketing): weekly briefing narrative ${p.weekLabel}`
    );
    if (stageBRes.error) {
      // Stage A succeeded but Stage B failed — surface the error but consider commit "done"
      return { committed: true, sha: stageARes.sha, url: stageARes.htmlUrl, error: `stageB: ${stageBRes.error}` };
    }
    stageBSha = stageBRes.sha;
    stageBHtmlUrl = stageBRes.htmlUrl;
  }

  if (stageARes.error) {
    return { committed: false, error: stageARes.error };
  }

  return { committed: true, sha: stageBSha ?? stageARes.sha, url: stageBHtmlUrl ?? stageARes.htmlUrl };
}

interface PutFileResult {
  sha?: string;
  htmlUrl?: string;
  error?: string;
}

async function putFile(token: string, path: string, content: string, message: string): Promise<PutFileResult> {
  const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`;
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };

  // GET to learn the existing SHA (so the PUT can update rather than reject as a duplicate path).
  let existingSha: string | undefined;
  const getRes = await fetch(`${url}?ref=${REPO_BRANCH}`, { headers });
  if (getRes.ok) {
    const body = (await getRes.json()) as { sha?: string };
    existingSha = body.sha;
  }
  // 404 here is fine — file doesn't exist yet, we'll create.

  const putRes = await fetch(url, {
    method: 'PUT',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      message,
      content: Buffer.from(content, 'utf-8').toString('base64'),
      branch: REPO_BRANCH,
      ...(existingSha ? { sha: existingSha } : {}),
    }),
  });

  if (!putRes.ok) {
    const body = await putRes.text();
    return { error: `GitHub PUT ${putRes.status}: ${body.slice(0, 300)}` };
  }

  const body = (await putRes.json()) as { content?: { sha?: string; html_url?: string } };
  return { sha: body.content?.sha, htmlUrl: body.content?.html_url };
}
