/**
 * Delivery for the weekly Marketing Director briefing — sends via Resend (email) and
 * commits the markdown to the repo via the GitHub REST API.
 *
 * Both calls fail soft: if env vars aren't set or the API call errors, we log and continue
 * so the cron itself stays green and the JSON response always returns the briefing content.
 */

import { resend } from '@/lib/email/resend-client';
import {
  renderBriefingEmail,
  type BriefingEmailData,
} from '@/lib/email/templates/marketing-briefing';
import { putFileToRepo } from '@/lib/github/put-file';

export interface DeliveryResult {
  email: { sent: boolean; error?: string };
  commit: { committed: boolean; sha?: string; url?: string; error?: string };
}

interface BriefingPayload {
  weekLabel: string;            // e.g. "2026-W18"
  stageA: string;               // deterministic markdown
  stageB: string | null;        // LLM narrative (null if not generated)
  to: string;                   // recipient email
  /** Structured payload for the chart-driven email render. If absent, falls back to plain markdown <pre> render. */
  emailData?: BriefingEmailData;
}

export async function deliverBriefing(payload: BriefingPayload): Promise<DeliveryResult> {
  const [emailRes, commitRes] = await Promise.all([
    sendEmail(payload).catch((e) => ({ sent: false, error: errMsg(e) })),
    commitToRepo(payload).catch((e) => ({ committed: false, error: errMsg(e) })),
  ]);
  return { email: emailRes, commit: commitRes };
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

/* -------------------- Email via Resend -------------------- */

async function sendEmail(p: BriefingPayload): Promise<{ sent: boolean; error?: string }> {
  if (!resend) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const subject = `Marketing weekly briefing — ${p.weekLabel}`;
  const html = p.emailData ? renderBriefingEmail(p.emailData) : renderHtml(p);
  const text = renderText(p);
  const fromName = 'Party On Delivery — Marketing Director';
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'orders@partyondelivery.com';

  await resend.emails.send({
    from: `${fromName} <${fromEmail}>`,
    to: p.to,
    subject,
    html,
    text,
  });
  return { sent: true };
}

function renderHtml(p: BriefingPayload): string {
  const stageBHtml = p.stageB
    ? `<hr/><h2>Narrative analysis (Claude)</h2><pre style="white-space:pre-wrap;font-family:inherit;font-size:15px;line-height:1.5;">${escapeHtml(p.stageB)}</pre>`
    : '<hr/><p style="color:#888"><em>Stage B narrative analysis was not generated this week — check the cron logs.</em></p>';

  return `<!doctype html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:760px;margin:0 auto;padding:32px;color:#111;">
  <h1 style="font-size:24px;margin-bottom:4px;">Marketing weekly briefing — ${p.weekLabel}</h1>
  <p style="color:#666;margin-top:0;font-size:14px;">Auto-generated by the Party On Delivery analytics pipeline. Also committed to the repo at <code>docs/marketing/weekly/${p.weekLabel}.md</code>.</p>
  <hr/>
  <h2>Data summary</h2>
  <pre style="white-space:pre-wrap;font-family:inherit;font-size:15px;line-height:1.5;">${escapeHtml(p.stageA)}</pre>
  ${stageBHtml}
</body>
</html>`;
}

function renderText(p: BriefingPayload): string {
  return [p.stageA, p.stageB ? `\n---\n\n${p.stageB}` : ''].join('');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/* -------------------- Commit to GitHub repo -------------------- */

async function commitToRepo(p: BriefingPayload): Promise<DeliveryResult['commit']> {
  const stageARes = await putFileToRepo({
    path: `docs/marketing/weekly/${p.weekLabel}.md`,
    content: p.stageA,
    message: `chore(marketing): weekly briefing ${p.weekLabel}`,
  });

  if (p.stageB) {
    const stageBRes = await putFileToRepo({
      path: `docs/marketing/weekly/${p.weekLabel}-director.md`,
      content: p.stageB,
      message: `chore(marketing): weekly briefing narrative ${p.weekLabel}`,
    });
    if (stageBRes.error && stageARes.committed) {
      return { committed: true, sha: stageARes.sha, url: stageARes.htmlUrl, error: `stageB: ${stageBRes.error}` };
    }
    if (stageBRes.committed) {
      return { committed: true, sha: stageBRes.sha, url: stageBRes.htmlUrl };
    }
  }

  if (!stageARes.committed) return { committed: false, error: stageARes.error };
  return { committed: true, sha: stageARes.sha, url: stageARes.htmlUrl };
}
